name: 'Example "Do something"'

on:
  workflow_dispatch:
    inputs:
      EX_INPUT_1:
        description: An example string input
        type: string
        required: false
      data:
        description: An example string input
        type: string
        required: false

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: Doing
        run: |
          echo 'Hello world!' 

      - name: Printing
        env:
          EX_INPUT: ${{ inputs.EX_INPUT_1 }}
          DATA: ${{ inputs.data }}
        run: |
          echo "EX_INPUT=$EX_INPUT"
          echo "data=$DATA"

  callback:
    needs: job
    uses: faubion-hbo/test-monitor/.github/workflows/monitor-callback.yaml@main
    with:
      GITHUB_CONTEXT: ${{ toJSON(github) }}
      WORKFLOW_RESULTS: ${{ toJSON(needs) }}
    secrets:
      CALLBACK_TOKEN: ${{ secrets.MONITOR_ROUNDTRIP_PAT }}
