name: 'Example "Do something"'

on:
  workflow_dispatch:

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: Doing
        run: |
          echo 'Hello world!' 

  callback:
    needs: job
    uses: faubion-hbo/test-monitor/.github/workflows/monitor-callback.yaml@main
    with:
      GITHUB_CONTEXT: ${{ toJSON(github) }}
      WORKFLOW_RESULTS: ${{ toJSON(needs) }}
      CALLBACK_TOKEN: ${{ secrets.MONITOR_ROUNDTRIP_PAT }}
